name: Execute CI

concurrency:
    group: test-us-east-2
    cancel-in-progress: false

on:
    pull_request:
        branches:
            - main
        paths:
            - "**.go"
            - "**.sum"
            - "**.mod"
            - "builder/**.go"
            - "datasource/**.sh"
            - "examples/**"
            - "scripts/run-examples.sh"
            - "GNUmakefile"
            - ".github/workflows/ci.yml"

permissions:
    contents: read

jobs:
    check-code:
        runs-on: ubuntu-latest
        environment: test-us-east-2
        steps:
            - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
            - uses: actions/setup-go@4a3601121dd01d1626a1e23e37211e3254c1c06c # v6
              with:
                  go-version-file: "go.mod"
            - name: Fmt
              run: |
                  go fmt ./...
                  echo "==> Checking that code complies with go fmt requirements..."
                  git diff --exit-code; if [ $? -eq 1 ]; then \
                  echo "Found files that are not fmt'ed."; \
                  echo "You can use the command: \`go fmt ./...\` to reformat code."; \
                  exit 1; \
                  fi
            - name: Generation
              run: |
                  make generate
                  echo "==> Checking that auto-generated code is not changed..."
                  git diff --exit-code; if [ $? -eq 1 ]; then \
                     echo "Found diffs in go generated code."; \
                     echo "You can use the command: \`make generate\` to reformat code."; \
                     exit 1; \
                  fi

    test:
        strategy:
            max-parallel: 1
            matrix:
                os: [ubuntu-24.04, windows-latest]
        runs-on: ${{ matrix.os }}
        environment: test-us-east-2
        steps:
            - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
            - name: 🧹 Frieza
              uses: outscale/frieza-github-actions/frieza-clean@master
              with:
                  access_key: ${{ secrets.OSC_ACCESS_KEY }}
                  secret_key: ${{ secrets.OSC_SECRET_KEY }}
                  region: ${{ secrets.OSC_REGION }}
            - name: Install Go
              uses: actions/setup-go@4a3601121dd01d1626a1e23e37211e3254c1c06c # v6
              with:
                  go-version-file: "go.mod"
            - name: Checkout code
              uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
            - name: Test
              env:
                  OSC_ACCESS_KEY: ${{secrets.OSC_ACCESS_KEY}}
                  OSC_SECRET_KEY: ${{secrets.OSC_SECRET_KEY}}
                  OSC_REGION: ${{secrets.OSC_REGION}}
              run: make test

    acceptance:
        needs: test
        runs-on: ubuntu-latest
        environment: test-us-east-2
        steps:
            - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
            - name: 🧹 Frieza
              uses: outscale/frieza-github-actions/frieza-clean@master
              with:
                  access_key: ${{ secrets.OSC_ACCESS_KEY }}
                  secret_key: ${{ secrets.OSC_SECRET_KEY }}
                  region: ${{ secrets.OSC_REGION }}
            - name: Install Go
              uses: actions/setup-go@4a3601121dd01d1626a1e23e37211e3254c1c06c # v6
              with:
                  go-version-file: "go.mod"
            - name: Run acceptance tests
              env:
                  OSC_ACCESS_KEY: ${{ secrets.OSC_ACCESS_KEY }}
                  OSC_SECRET_KEY: ${{ secrets.OSC_SECRET_KEY }}
                  OSC_REGION: ${{ secrets.OSC_REGION }}
              run: make testacc

    build:
        strategy:
            matrix:
                goos: ["linux", "darwin", "windows"]
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6

            - name: Set up Go
              uses: actions/setup-go@4a3601121dd01d1626a1e23e37211e3254c1c06c # v6
              with:
                  go-version-file: "go.mod"
            - name: Build
              run: GOOS=${{matrix.goos}} go build -v -o packer-plugin-outscale_${{matrix.goos}}
            - name: Upload a Build Artifact
              uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7
              with:
                  name: packer-plugin-outscale_${{matrix.goos}}
                  path: ./packer-plugin-outscale_${{matrix.goos}}
