name: Compliance

on:
  pull_request:
    branches: [ main ]

permissions:
  contents: read

jobs:
  compliance:
    runs-on: ubuntu-latest
    steps:
    - name: ⬇️ Checkout
      uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
      with:
        persist-credentials: false
    - name: Plumber
      uses: outscale/.github/pipeline-compliance@f4952618256a12ea89d93ba7105866b80bd62266 # v1.0.0
