name: Compliance

on:
  pull_request:
    branches: [ main ]

permissions:
  contents: read

jobs:
  compliance:
    runs-on: ubuntu-latest
    steps:
    - name: ⬇️ Checkout
      uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
      with:
        persist-credentials: false
    - name: Plumber
      uses: outscale/.github/pipeline-compliance@dfa747ea77f97fdc5a0bf745e4933a8d68631f89 # v1.1.2
