name: Packer examples tests
on:
  pull_request:
    branches:
      - master
    paths:
      - 'examples/**.pkr.hcl'
      - 'examples/**.sh'
      - 'examples/**.yml'
      - 'scripts/run-examples.sh'
      - 'GNUmakefile'
      - '.github/workflows/packer-examples.yaml'
  schedule:
    - cron: '30 02 * * *'
  workflow_dispatch:

jobs:
  Packer_examples_tests:
    environment: test-us-east-2
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: 🧹 Frieza
        uses: outscale/frieza-github-actions/frieza-clean@master
        with:
          access_key: ${{ secrets.OSC_ACCESS_KEY }}
          secret_key: ${{ secrets.OSC_SECRET_KEY }}
          region: ${{ secrets.OSC_REGION }}

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'

      - name: Build packer-plugin-outscale
        run: make build

      - name: "Install Ansible"
        uses: alex-oleshkevich/setup-ansible@v1.0.1
        with:
          version: "latest"

      - name: Setup `packer`
        uses: hashicorp/setup-packer@main
        with:
          version: "latest"

      - name: Run Packer examples
        run: ./scripts/run-examples.sh
        env:
          OSC_ACCESS_KEY: ${{secrets.OSC_ACCESS_KEY}}
          OSC_SECRET_KEY: ${{secrets.OSC_SECRET_KEY}}
          OSC_REGION: ${{secrets.OSC_REGION}}
